#  docker-compose -f docker-compose.yml config check validate config
version: "3.7"
services:
  mytest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mytest
    working_dir: /var/www/html
    restart: "no"
    ports:
      - "8101:8101"
    expose:
      - "8101"
    labels:
      com.docker.compose.project: "mytest"
    environment:
      TEST_ENV: "mytest.local.com"